# Generated by Django 5.2 on 2026-08-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US-Dollar'), ('GBP', 'Britisches Pfund'), ('BGN', 'Bulgarischer Lew')], default='EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['category', '-created_at'], name='idx_prod_active_cat_created'), models.Index(condition=models.Q(('is_active', True)), fields=['price'], name='idx_prod_price'), models.Index(condition=models.Q(('is_active', True)), fields=['-created_at', '-id'], name='idx_prod_created_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative')],
            },
        ),
    ]
